import { Organisation, Profile, Quiz, TournamentRound, Question, Entry, Winner, Referral } from './types';

export const MOCK_ORGS: Organisation[] = [
  {
    id: 'org-1',
    name: 'Acme Tech Academy',
    slug: 'acme-tech',
    logo_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
    plan: 'free',
    quizzes_created_this_month: 2, // At Free plan limit for demonstration!
    settings: {
      primary_color: '#4f46e5',
      allow_public_registration: true,
      banner_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80',
    },
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'org-2',
    name: 'Cyber Arena Labs',
    slug: 'cyber-arena',
    logo_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    plan: 'plus',
    quizzes_created_this_month: 5,
    settings: {
      primary_color: '#059669',
      allow_public_registration: true,
    },
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const MOCK_USERS: Profile[] = [
  {
    id: 'user-superadmin',
    username: 'superadmin',
    email: 'superadmin@gmail.com',
    full_name: 'Elena Rostova (Google)',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    role: 'superadmin',
    auth_provider: 'google',
    org_id: null,
    referral_code: 'SUPER99',
    referred_by: null,
    total_points: 1500,
    total_referrals: 12,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'user-admin',
    username: 'marcus_vance',
    email: 'marcus.vance@gmail.com',
    full_name: 'Prof. Marcus Vance (Google Auth)',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    role: 'admin',
    auth_provider: 'google',
    org_id: 'org-1',
    referral_code: 'ACME2026',
    referred_by: null,
    total_points: 420,
    total_referrals: 5,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'user-participant-1',
    username: 'alexchen',
    email: 'alex.chen@student.io',
    full_name: 'Alex Chen',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&auto=format&fit=crop&q=80',
    role: 'participant',
    auth_provider: 'credentials',
    org_id: 'org-1',
    referral_code: 'ALEX2026',
    referred_by: 'user-admin',
    total_points: 340,
    total_referrals: 3,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'user-participant-2',
    username: 'sarah_j',
    email: 'sarah.j@developer.net',
    full_name: 'Sarah Jenkins',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&auto=format&fit=crop&q=80',
    role: 'participant',
    auth_provider: 'credentials',
    org_id: 'org-1',
    referral_code: 'SARAH88',
    referred_by: 'user-participant-1',
    total_points: 290,
    total_referrals: 1,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const MOCK_ROUNDS: TournamentRound[] = [
  {
    id: 'round-1',
    quiz_id: 'quiz-tournament-1',
    round_number: 1,
    title: 'Round 1: Speed Qualifier (Prelims)',
    scheduled_start_time: new Date(Date.now() - 2 * 3600000).toISOString(),
    scheduled_end_time: new Date(Date.now() + 24 * 3600000).toISOString(),
    min_score_to_qualify: 8,
    min_correct_to_qualify: 1,
    max_qualifiers: 50,
    status: 'active',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'round-2',
    quiz_id: 'quiz-tournament-1',
    round_number: 2,
    title: 'Round 2: Grand Finals & System Architecture',
    scheduled_start_time: new Date(Date.now() + 24 * 3600000).toISOString(),
    scheduled_end_time: new Date(Date.now() + 48 * 3600000).toISOString(),
    min_score_to_qualify: 15,
    min_correct_to_qualify: 2,
    max_qualifiers: 10,
    status: 'pending',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'q-1',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    order_index: 1,
    question_text: 'What data structure does PostgreSQL utilize under the hood by default for primary key indexes?',
    attachment_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format&fit=crop&q=80',
    attachment_type: 'image',
    points: 10,
    time_limit_sec: 15,
    options: [
      { id: 'opt-1-1', text: 'B-Tree Index', is_correct: true, explanation: 'Postgres uses balanced B-Trees by default for standard indexes.' },
      { id: 'opt-1-2', text: 'Hash Map Table', is_correct: false },
      { id: 'opt-1-3', text: 'Skip List Structure', is_correct: false },
      { id: 'opt-1-4', text: 'Radix Trie', is_correct: false },
    ],
    explanation: 'PostgreSQL defaults to B-Tree index structures because they optimize search, insertion, and range queries on block storage.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-2',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    order_index: 2,
    question_text: 'In Supabase Row Level Security (RLS), which SQL function accesses the authenticated user ID from the JWT session token?',
    attachment_url: null,
    attachment_type: 'none',
    points: 10,
    time_limit_sec: 15,
    options: [
      { id: 'opt-2-1', text: 'auth.uid()', is_correct: true, explanation: 'auth.uid() is provided by Supabase in the auth schema.' },
      { id: 'opt-2-2', text: 'current_user_id()', is_correct: false },
      { id: 'opt-2-3', text: 'supabase.session()', is_correct: false },
      { id: 'opt-2-4', text: 'request.jwt_claim()', is_correct: false },
    ],
    explanation: 'auth.uid() extracts the sub (subject / UUID) claim from the signed Supabase JWT.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-3',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    order_index: 3,
    question_text: 'Examine the system latency diagram below. Which distributed consensus algorithm ensures zero-loss multi-leader data synchronization?',
    attachment_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    attachment_type: 'image',
    points: 10,
    time_limit_sec: 20,
    options: [
      { id: 'opt-3-1', text: 'Raft Consensus Protocol', is_correct: true },
      { id: 'opt-3-2', text: 'Round Robin DNS', is_correct: false },
      { id: 'opt-3-3', text: 'Greedy Heuristic Routing', is_correct: false },
      { id: 'opt-3-4', text: 'Exponential Backoff Polling', is_correct: false },
    ],
    explanation: 'Raft is an understandable consensus algorithm designed for fault-tolerant distributed state machines.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-4',
    quiz_id: 'quiz-single-1',
    round_id: null,
    order_index: 1,
    question_text: 'Which React 19 / Next.js 14 feature executes purely on the server and generates 0 bytes of client-side JavaScript bundle?',
    attachment_url: null,
    attachment_type: 'none',
    points: 10,
    time_limit_sec: 20,
    options: [
      { id: 'opt-4-1', text: 'React Server Components (RSC)', is_correct: true },
      { id: 'opt-4-2', text: 'useServerState Hook', is_correct: false },
      { id: 'opt-4-3', text: 'Client Hydration Proxy', is_correct: false },
      { id: 'opt-4-4', text: 'Browser Service Worker Thread', is_correct: false },
    ],
    explanation: 'RSC streams rendered HTML and metadata to the client without sending component code.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'q-5',
    quiz_id: 'quiz-single-1',
    round_id: null,
    order_index: 2,
    question_text: 'What header does Next.js middleware inspect to implement tenant subdomain isolation in multi-tenant architectures?',
    attachment_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    attachment_type: 'image',
    points: 10,
    time_limit_sec: 20,
    options: [
      { id: 'opt-5-1', text: 'x-forwarded-host or host', is_correct: true },
      { id: 'opt-5-2', text: 'accept-encoding', is_correct: false },
      { id: 'opt-5-3', text: 'user-agent-locale', is_correct: false },
      { id: 'opt-5-4', text: 'content-disposition', is_correct: false },
    ],
    explanation: 'The host header allows middleware to extract subdomain slugs and rewrite paths dynamically.',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: 'quiz-tournament-1',
    org_id: 'org-1',
    title: 'AI & Web3 National Championship 2026',
    description: 'A prestigious multi-round tournament testing modern cloud systems, PostgreSQL internals, and distributed architecture with speed-based points decay.',
    banner_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    quiz_type: 'tournament',
    progression_mode: 'automatic',
    scoring_strategy: 'time_decay',
    base_points_per_question: 10,
    time_limit_per_question_sec: 15,
    total_time_limit_sec: null,
    shuffle_questions: true,
    shuffle_options: true,
    enable_referral_bonus: true,
    referral_bonus_points: 25,
    status: 'published',
    max_participants: 100, // Free plan limit
    start_time: new Date(Date.now() - 2 * 3600000).toISOString(),
    end_time: new Date(Date.now() + 48 * 3600000).toISOString(),
    created_by: 'user-admin',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    organisation: MOCK_ORGS[0],
    rounds: MOCK_ROUNDS,
    questions_count: 3,
  },
  {
    id: 'quiz-single-1',
    org_id: 'org-1',
    title: 'Frontend Masters Flash Sprint',
    description: 'Fast-paced single competition testing React 19, TypeScript 5.7, and Next.js App Router performance optimizations.',
    banner_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&auto=format&fit=crop&q=80',
    quiz_type: 'single',
    progression_mode: 'manual',
    scoring_strategy: 'fixed',
    base_points_per_question: 10,
    time_limit_per_question_sec: 20,
    total_time_limit_sec: null,
    shuffle_questions: true,
    shuffle_options: true,
    enable_referral_bonus: false,
    referral_bonus_points: 0,
    status: 'published',
    max_participants: 100,
    start_time: new Date(Date.now() - 5 * 3600000).toISOString(),
    end_time: new Date(Date.now() + 72 * 3600000).toISOString(),
    created_by: 'user-admin',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    organisation: MOCK_ORGS[0],
    questions_count: 2,
  },
  {
    id: 'quiz-cyber-2',
    org_id: 'org-2',
    title: 'Cybersecurity Blue Team Invitational',
    description: 'Manual round progression tournament focusing on penetration testing protocols, network defense, and zero-trust authentication.',
    banner_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    quiz_type: 'tournament',
    progression_mode: 'manual',
    scoring_strategy: 'time_decay',
    base_points_per_question: 10,
    time_limit_per_question_sec: 15,
    total_time_limit_sec: null,
    shuffle_questions: false,
    shuffle_options: true,
    enable_referral_bonus: true,
    referral_bonus_points: 15,
    status: 'published',
    max_participants: null, // Plus plan unlimited
    start_time: new Date().toISOString(),
    end_time: new Date(Date.now() + 96 * 3600000).toISOString(),
    created_by: 'user-superadmin',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    organisation: MOCK_ORGS[1],
    questions_count: 5,
  }
];

export const MOCK_ENTRIES: Entry[] = [
  {
    id: 'entry-1',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    user_id: 'user-participant-1',
    score: 26,
    total_correct: 3,
    total_time_taken_ms: 12400,
    qualified_for_next_round: true,
    status: 'submitted',
    started_at: new Date(Date.now() - 3600000).toISOString(),
    completed_at: new Date(Date.now() - 3500000).toISOString(),
    user: MOCK_USERS[2],
  },
  {
    id: 'entry-2',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    user_id: 'user-participant-2',
    score: 19,
    total_correct: 2,
    total_time_taken_ms: 18200,
    qualified_for_next_round: true,
    status: 'submitted',
    started_at: new Date(Date.now() - 7200000).toISOString(),
    completed_at: new Date(Date.now() - 7100000).toISOString(),
    user: MOCK_USERS[3],
  },
];

export const MOCK_WINNERS: Winner[] = [
  {
    id: 'winner-1',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    user_id: 'user-participant-1',
    rank: 1,
    final_score: 26,
    total_time_taken_ms: 12400,
    prize_or_badge: 'Gold Tier Qualifier',
    created_at: new Date().toISOString(),
    user: MOCK_USERS[2],
  },
  {
    id: 'winner-2',
    quiz_id: 'quiz-tournament-1',
    round_id: 'round-1',
    user_id: 'user-participant-2',
    rank: 2,
    final_score: 19,
    total_time_taken_ms: 18200,
    prize_or_badge: 'Silver Tier Qualifier',
    created_at: new Date().toISOString(),
    user: MOCK_USERS[3],
  },
];

export const MOCK_REFERRALS: Referral[] = [
  {
    id: 'ref-1',
    referrer_id: 'user-admin',
    referee_id: 'user-participant-1',
    quiz_id: 'quiz-tournament-1',
    bonus_points_awarded: 25,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    referee: MOCK_USERS[2],
    referrer: MOCK_USERS[1],
  },
  {
    id: 'ref-2',
    referrer_id: 'user-participant-1',
    referee_id: 'user-participant-2',
    quiz_id: 'quiz-tournament-1',
    bonus_points_awarded: 25,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    referee: MOCK_USERS[3],
    referrer: MOCK_USERS[2],
  },
];
